"""InMemoryLoadMatchRepository (Task A.3)."""

from __future__ import annotations

from typing import Dict, List, Optional

from app.core.enums import LoadMatchStatus
from app.repositories.exceptions import ConflictError, NotFoundError
from app.repositories.models import LoadMatch, new_id

_ACTIVE_STATUSES = {LoadMatchStatus.PROPOSED, LoadMatchStatus.ACCEPTED}


class InMemoryLoadMatchRepository:
    def __init__(self) -> None:
        self._by_id: Dict[str, LoadMatch] = {}
        # No seed file for load_matches — matches are generated by the
        # matching engine at runtime, not fixture data (unlike
        # users/vehicles/loads, which Kishor's seed export covers).

    async def create(
        self,
        load_id: str,
        vehicle_id: str,
        status: LoadMatchStatus,
        match_score: Optional[float],
    ) -> LoadMatch:
        if status in _ACTIVE_STATUSES:
            for existing in self._by_id.values():
                if (
                    existing.vehicle_id == vehicle_id
                    and existing.load_id != load_id
                    and existing.status in _ACTIVE_STATUSES
                ):
                    raise ConflictError(
                        f"Vehicle {vehicle_id!r} already has an active match "
                        f"for a different load ({existing.load_id!r}) — "
                        f"'match no longer available'."
                    )
        match = LoadMatch(
            id=new_id(), load_id=load_id, vehicle_id=vehicle_id, status=status, match_score=match_score
        )
        self._by_id[match.id] = match
        return match

    async def get_by_load_and_vehicle(
        self, load_id: str, vehicle_id: str
    ) -> Optional[LoadMatch]:
        for match in self._by_id.values():
            if match.load_id == load_id and match.vehicle_id == vehicle_id:
                return match
        return None

    async def update_status(self, match_id: str, status: LoadMatchStatus) -> None:
        match = self._by_id.get(match_id)
        if match is None:
            raise NotFoundError(f"No load match with id={match_id!r}")
        match.status = status

    async def list_by_load(self, load_id: str) -> List[LoadMatch]:
        return [m for m in self._by_id.values() if m.load_id == load_id]
